---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: jupyter-datascience-ubi8-python-3-8-
commonLabels:
  app: jupyter-datascience-ubi8-python-3-8
resources:
  - service.yaml
  - statefulset.yaml
images:
  - name: quay.io/opendatahub/workbench-images
    newName: lab-docker.wwtatc.com:5004/opendatahub/workbench-images
    newTag: jupyter-datascience-ubi8-python-3.8-2023b_20240208
